"""empty message

Revision ID: 3b73ea06db52
Revises: 46d473c26188
Create Date: 2026-04-08 23:18:25.100233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b73ea06db52'
down_revision: Union[str, None] = '46d473c26188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_folder_id', table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_folder_id', 'documents', ['folder_id'], unique=False)
    # ### end Alembic commands ###
