"""Add note_type to meeting notes

Revision ID: 44a7f68b2a74
Revises: b5700aa37af9
Create Date: 2026-04-07 15:49:59.958340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a7f68b2a74'
down_revision: Union[str, None] = 'b5700aa37af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_notes', sa.Column('note_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_notes', 'note_type')
    # ### end Alembic commands ###
