"""add_task_type_column

Revision ID: 51c7c579f9e3
Revises: f10f332b35f7
Create Date: 2026-04-03 23:10:58.622279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c7c579f9e3'
down_revision: Union[str, None] = 'f10f332b35f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_tasks', sa.Column('task_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_tasks', 'task_type')
    # ### end Alembic commands ###
