"""Add comment nested replies and reactions

Revision ID: 5484509221af
Revises: eb829ec25c39
Create Date: 2026-04-12 02:11:05.725333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5484509221af'
down_revision: Union[str, None] = 'eb829ec25c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_entry_comment_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_like', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['timeline_entry_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_entry_comment_reactions_comment_id'), 'timeline_entry_comment_reactions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_timeline_entry_comment_reactions_id'), 'timeline_entry_comment_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_entry_comment_reactions_user_id'), 'timeline_entry_comment_reactions', ['user_id'], unique=False)
    op.add_column('timeline_entry_comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_timeline_entry_comments_parent_id'), 'timeline_entry_comments', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'timeline_entry_comments', 'timeline_entry_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeline_entry_comments', type_='foreignkey')
    op.drop_index(op.f('ix_timeline_entry_comments_parent_id'), table_name='timeline_entry_comments')
    op.drop_column('timeline_entry_comments', 'parent_id')
    op.drop_index(op.f('ix_timeline_entry_comment_reactions_user_id'), table_name='timeline_entry_comment_reactions')
    op.drop_index(op.f('ix_timeline_entry_comment_reactions_id'), table_name='timeline_entry_comment_reactions')
    op.drop_index(op.f('ix_timeline_entry_comment_reactions_comment_id'), table_name='timeline_entry_comment_reactions')
    op.drop_table('timeline_entry_comment_reactions')
    # ### end Alembic commands ###
