"""Add post level reactions

Revision ID: 7023168cee50
Revises: 5484509221af
Create Date: 2026-04-12 02:36:51.195490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7023168cee50'
down_revision: Union[str, None] = '5484509221af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_entry_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_like', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['timeline_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_entry_reactions_entry_id'), 'timeline_entry_reactions', ['entry_id'], unique=False)
    op.create_index(op.f('ix_timeline_entry_reactions_id'), 'timeline_entry_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_entry_reactions_user_id'), 'timeline_entry_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_entry_reactions_user_id'), table_name='timeline_entry_reactions')
    op.drop_index(op.f('ix_timeline_entry_reactions_id'), table_name='timeline_entry_reactions')
    op.drop_index(op.f('ix_timeline_entry_reactions_entry_id'), table_name='timeline_entry_reactions')
    op.drop_table('timeline_entry_reactions')
    # ### end Alembic commands ###
