"""add_missing_user_notification_columns

Revision ID: 86a107e46abc
Revises: a56ab98a814d
Create Date: 2026-04-07 14:46:06.007829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a107e46abc'
down_revision: Union[str, None] = 'a56ab98a814d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('documents', 'stored_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('teams', sa.Column('ai_sensitivity', sa.Integer(), nullable=True))
    op.add_column('timeline_entries', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_timeline_entries_team_id'), 'timeline_entries', ['team_id'], unique=False)
    op.drop_constraint(op.f('timeline_entries_project_id_fkey'), 'timeline_entries', type_='foreignkey')
    op.create_foreign_key(None, 'timeline_entries', 'teams', ['team_id'], ['id'])
    op.drop_column('timeline_entries', 'project_id')
    op.add_column('user_roles', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_roles_team_id'), 'user_roles', ['team_id'], unique=False)
    op.create_foreign_key(None, 'user_roles', 'teams', ['team_id'], ['id'])
    op.add_column('users', sa.Column('notify_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_dashboard', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_deadline', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_deadline')
    op.drop_column('users', 'notify_dashboard')
    op.drop_column('users', 'notify_email')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_index(op.f('ix_user_roles_team_id'), table_name='user_roles')
    op.drop_column('user_roles', 'team_id')
    op.add_column('timeline_entries', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timeline_entries', type_='foreignkey')
    op.create_foreign_key(op.f('timeline_entries_project_id_fkey'), 'timeline_entries', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_timeline_entries_team_id'), table_name='timeline_entries')
    op.drop_column('timeline_entries', 'team_id')
    op.drop_column('teams', 'ai_sensitivity')
    op.alter_column('documents', 'stored_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'session_id')
    # ### end Alembic commands ###
