"""add_missing_user_notification_columns

Revision ID: 86a107e46abc
Revises: a56ab98a814d
Create Date: 2026-04-07 14:46:06.007829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '86a107e46abc'
down_revision: Union[str, None] = 'a56ab98a814d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table: str, column: str) -> bool:
    bind = op.get_bind()
    return column in [c["name"] for c in inspect(bind).get_columns(table)]


def _index_exists(table: str, index: str) -> bool:
    bind = op.get_bind()
    return any(idx["name"] == index for idx in inspect(bind).get_indexes(table))


def _fk_exists(table: str, referred_table: str) -> bool:
    bind = op.get_bind()
    return any(
        fk["referred_table"] == referred_table
        for fk in inspect(bind).get_foreign_keys(table)
    )


def _constraint_exists(table: str, constraint: str) -> bool:
    bind = op.get_bind()
    return any(fk["name"] == constraint for fk in inspect(bind).get_foreign_keys(table))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All add_column / create_index calls are guarded because create_all() may have
    # already created these columns before migrations ran (schema drift).
    if not _column_exists("chat_messages", "session_id"):
        op.add_column('chat_messages', sa.Column('session_id', sa.String(), nullable=True))
    if not _index_exists("chat_messages", op.f('ix_chat_messages_session_id')):
        op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('documents', 'stored_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    if not _column_exists("teams", "ai_sensitivity"):
        op.add_column('teams', sa.Column('ai_sensitivity', sa.Integer(), nullable=True))
    if not _column_exists("timeline_entries", "team_id"):
        op.add_column('timeline_entries', sa.Column('team_id', sa.Integer(), nullable=False))
    if not _index_exists("timeline_entries", op.f('ix_timeline_entries_team_id')):
        op.create_index(op.f('ix_timeline_entries_team_id'), 'timeline_entries', ['team_id'], unique=False)
    if _constraint_exists("timeline_entries", op.f('timeline_entries_project_id_fkey')):
        op.drop_constraint(op.f('timeline_entries_project_id_fkey'), 'timeline_entries', type_='foreignkey')
    if not _fk_exists("timeline_entries", "teams"):
        op.create_foreign_key(None, 'timeline_entries', 'teams', ['team_id'], ['id'])
    if _column_exists("timeline_entries", "project_id"):
        op.drop_column('timeline_entries', 'project_id')
    if not _column_exists("user_roles", "team_id"):
        op.add_column('user_roles', sa.Column('team_id', sa.Integer(), nullable=True))
    if not _index_exists("user_roles", op.f('ix_user_roles_team_id')):
        op.create_index(op.f('ix_user_roles_team_id'), 'user_roles', ['team_id'], unique=False)
    if not _fk_exists("user_roles", "teams"):
        op.create_foreign_key(None, 'user_roles', 'teams', ['team_id'], ['id'])
    if not _column_exists("users", "notify_email"):
        op.add_column('users', sa.Column('notify_email', sa.Boolean(), nullable=True))
    if not _column_exists("users", "notify_dashboard"):
        op.add_column('users', sa.Column('notify_dashboard', sa.Boolean(), nullable=True))
    if not _column_exists("users", "notify_deadline"):
        op.add_column('users', sa.Column('notify_deadline', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_deadline')
    op.drop_column('users', 'notify_dashboard')
    op.drop_column('users', 'notify_email')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_index(op.f('ix_user_roles_team_id'), table_name='user_roles')
    op.drop_column('user_roles', 'team_id')
    op.add_column('timeline_entries', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timeline_entries', type_='foreignkey')
    op.create_foreign_key(op.f('timeline_entries_project_id_fkey'), 'timeline_entries', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_timeline_entries_team_id'), table_name='timeline_entries')
    op.drop_column('timeline_entries', 'team_id')
    op.drop_column('teams', 'ai_sensitivity')
    op.alter_column('documents', 'stored_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'session_id')
    # ### end Alembic commands ###
