"""add author and tags to timeline

Revision ID: 97572d2011de
Revises: a834f29ee2a6
Create Date: 2026-04-04 11:20:45.409686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97572d2011de'
down_revision: Union[str, None] = 'a834f29ee2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_entries', sa.Column('author_name', sa.String(), nullable=True))
    op.add_column('timeline_entries', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('timeline_entries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_entries', 'updated_at')
    op.drop_column('timeline_entries', 'tags')
    op.drop_column('timeline_entries', 'author_name')
    # ### end Alembic commands ###
