"""add_verification_columns

Revision ID: a29b29815d1c
Revises: c3dbd884547b
Create Date: 2026-03-28 15:29:03.199588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29b29815d1c'
down_revision: Union[str, None] = 'c3dbd884547b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_verification_sent', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_sent')
    # ### end Alembic commands ###
