"""Add settings fields

Revision ID: a56ab98a814d
Revises: 9b870d98ae44
Create Date: 2026-04-06 00:20:53.006396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56ab98a814d'
down_revision: Union[str, None] = '9b870d98ae44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('ai_sensitivity', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('notify_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_dashboard', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_deadline', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_deadline')
    op.drop_column('users', 'notify_dashboard')
    op.drop_column('users', 'notify_email')
    op.drop_column('teams', 'ai_sensitivity')
    # ### end Alembic commands ###
