"""Add drive fields to documents

Revision ID: b7e3d1f4a289
Revises: a56ab98a814d
Create Date: 2026-04-07 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e3d1f4a289'
down_revision: Union[str, None] = 'a56ab98a814d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('drive_file_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('refresh_interval_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'refresh_interval_hours')
    op.drop_column('documents', 'last_synced_at')
    op.drop_column('documents', 'drive_file_id')
    op.drop_column('documents', 'source_url')
    # ### end Alembic commands ###
