"""describe change

Revision ID: d845caf777e9
Revises: 3b73ea06db52
Create Date: 2026-04-09 19:02:53.755140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd845caf777e9'
down_revision: Union[str, None] = '3b73ea06db52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('drive_file_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('refresh_interval_hours', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'documents', 'documents', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 'folder_id')
    op.drop_column('documents', 'refresh_interval_hours')
    op.drop_column('documents', 'last_synced_at')
    op.drop_column('documents', 'drive_file_id')
    op.drop_column('documents', 'source_url')
    # ### end Alembic commands ###
