"""Add content to meeting notes

Revision ID: d9f1a8c7b6e5
Revises: 44a7f68b2a74
Create Date: 2026-04-07 20:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f1a8c7b6e5'
down_revision: Union[str, None] = '44a7f68b2a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_notes', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_notes', 'content')
    # ### end Alembic commands ###
