"""Add is_trashed to meeting_notes

Revision ID: dacfc08e3ec5
Revises: d9f1a8c7b6e5
Create Date: 2026-04-07 21:04:56.784621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dacfc08e3ec5'
down_revision: Union[str, None] = 'd9f1a8c7b6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meeting_notes_folder_id_fkey'), 'meeting_notes', type_='foreignkey')
    op.drop_index(op.f('ix_note_folders_id'), table_name='note_folders')
    op.drop_table('note_folders')
    op.add_column('meeting_notes', sa.Column('is_trashed', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'meeting_notes', 'meeting_folders', ['folder_id'], ['id'])
    op.drop_column('meeting_notes', 'is_deleted')
    op.drop_column('meeting_notes', 'canvas_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_notes', sa.Column('canvas_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('meeting_notes', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'meeting_notes', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_notes_folder_id_fkey'), 'meeting_notes', 'note_folders', ['folder_id'], ['id'])
    op.drop_column('meeting_notes', 'is_trashed')
    op.create_table('note_folders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['note_folders.id'], name=op.f('note_folders_parent_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('note_folders_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('note_folders_pkey'))
    )
    op.create_index(op.f('ix_note_folders_id'), 'note_folders', ['id'], unique=False)
    # ### end Alembic commands ###
