"""add_timeline_features

Revision ID: eb829ec25c39
Revises: a1b2c3d4e5f7
Create Date: 2026-04-12 00:41:53.178702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb829ec25c39'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['timeline_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_attachments_entry_id'), 'timeline_attachments', ['entry_id'], unique=False)
    op.create_index(op.f('ix_timeline_attachments_id'), 'timeline_attachments', ['id'], unique=False)
    op.create_table('timeline_entry_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['timeline_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_entry_comments_entry_id'), 'timeline_entry_comments', ['entry_id'], unique=False)
    op.create_index(op.f('ix_timeline_entry_comments_id'), 'timeline_entry_comments', ['id'], unique=False)
    op.create_table('timeline_entry_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('edited_by_id', sa.Integer(), nullable=False),
    sa.Column('previous_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['timeline_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_entry_versions_entry_id'), 'timeline_entry_versions', ['entry_id'], unique=False)
    op.create_index(op.f('ix_timeline_entry_versions_id'), 'timeline_entry_versions', ['id'], unique=False)
    op.drop_table('whiteboard_states')
    op.drop_index(op.f('ix_documents_folder_id'), table_name='documents')
    op.drop_constraint(op.f('user_roles_project_id_fkey'), 'user_roles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_roles_project_id_fkey'), 'user_roles', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_documents_folder_id'), 'documents', ['folder_id'], unique=False)
    op.create_table('whiteboard_states',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('whiteboard_states_team_id_fkey')),
    sa.PrimaryKeyConstraint('team_id', name=op.f('whiteboard_states_pkey'))
    )
    op.drop_index(op.f('ix_timeline_entry_versions_id'), table_name='timeline_entry_versions')
    op.drop_index(op.f('ix_timeline_entry_versions_entry_id'), table_name='timeline_entry_versions')
    op.drop_table('timeline_entry_versions')
    op.drop_index(op.f('ix_timeline_entry_comments_id'), table_name='timeline_entry_comments')
    op.drop_index(op.f('ix_timeline_entry_comments_entry_id'), table_name='timeline_entry_comments')
    op.drop_table('timeline_entry_comments')
    op.drop_index(op.f('ix_timeline_attachments_id'), table_name='timeline_attachments')
    op.drop_index(op.f('ix_timeline_attachments_entry_id'), table_name='timeline_attachments')
    op.drop_table('timeline_attachments')
    # ### end Alembic commands ###
