"""Add collaborators and impact

Revision ID: f5acceabd724
Revises: 97572d2011de
Create Date: 2026-04-04 13:07:42.514471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5acceabd724'
down_revision: Union[str, None] = '97572d2011de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_entries', sa.Column('collaborators', sa.String(), nullable=True))
    op.add_column('timeline_entries', sa.Column('impact_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_entries', 'impact_level')
    op.drop_column('timeline_entries', 'collaborators')
    # ### end Alembic commands ###
