"""add_session_id_to_chat_messages

Revision ID: fcd81f18902f
Revises: ca4977d47b77
Create Date: 2026-03-31 22:51:22.174006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd81f18902f'
down_revision: Union[str, None] = 'ca4977d47b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'session_id')
    # ### end Alembic commands ###
